services:
    chrome-extension:
        container_name: chrome-extension
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        command: sh -c "yarn install && yarn dev --host"
        ports:
            - 3015:3001
        volumes:
            - .:/app
